/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { lazyRouteComponent } from '@tanstack/react-router'

const DashboardRouteImport = lazyRouteComponent(() => import('./routes/dashboard'))
const IndexRouteImport = lazyRouteComponent(() => import('./routes/index'))
const DashboardIndexRouteImport = lazyRouteComponent(() => import('./routes/dashboard/index'))
const DashboardTarefasRouteImport = lazyRouteComponent(() => import('./routes/dashboard/tarefas'))
const DashboardStatusRouteImport = lazyRouteComponent(() => import('./routes/dashboard/status'))
const DashboardRedacaoRouteImport = lazyRouteComponent(() => import('./routes/dashboard/redacao'))
const DashboardPreparaspRouteImport = lazyRouteComponent(() => import('./routes/dashboard/preparasp'))
const DashboardLeiaspRouteImport = lazyRouteComponent(() => import('./routes/dashboard/leiasp'))
const DashboardKhanRouteImport = lazyRouteComponent(() => import('./routes/dashboard/khan'))
const DashboardApostilasRouteImport = lazyRouteComponent(() => import('./routes/dashboard/apostilas'))
const ApiPdfProxyRouteImport = lazyRouteComponent(() => import('./routes/api/pdf-proxy'))
const ApiStatusEndpointRouteImport = lazyRouteComponent(() => import('./routes/api/status.$endpoint'))
const ApiProxySplatRouteImport = lazyRouteComponent(() => import('./routes/api/proxy.$'))
const ApiPreparaspSplatRouteImport = lazyRouteComponent(() => import('./routes/api/preparasp.$'))
const ApiLeiaspSplatRouteImport = lazyRouteComponent(() => import('./routes/api/leiasp.$'))
const ApiCupiditysSplatRouteImport = lazyRouteComponent(() => import('./routes/api/cupiditys.$'))
const ApiCatalystCompleteRouteImport = lazyRouteComponent(() => import('./routes/api/catalyst.complete'))
const ApiAiGenerateRouteImport = lazyRouteComponent(() => import('./routes/api/ai.generate'))
const ApiCatalystJobJobIdRouteImport = lazyRouteComponent(() => import('./routes/api/catalyst.job.$jobId'))

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTarefasRoute = DashboardTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatusRoute = DashboardStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRedacaoRoute = DashboardRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreparaspRoute = DashboardPreparaspRouteImport.update({
  id: '/preparasp',
  path: '/preparasp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeiaspRoute = DashboardLeiaspRouteImport.update({
  id: '/leiasp',
  path: '/leiasp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKhanRoute = DashboardKhanRouteImport.update({
  id: '/khan',
  path: '/khan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApostilasRoute = DashboardApostilasRouteImport.update({
  id: '/apostilas',
  path: '/apostilas',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPdfProxyRoute = ApiPdfProxyRouteImport.update({
  id: '/api/pdf-proxy',
  path: '/api/pdf-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusEndpointRoute = ApiStatusEndpointRouteImport.update({
  id: '/api/status/$endpoint',
  path: '/api/status/$endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreparaspSplatRoute = ApiPreparaspSplatRouteImport.update({
  id: '/api/preparasp/$',
  path: '/api/preparasp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeiaspSplatRoute = ApiLeiaspSplatRouteImport.update({
  id: '/api/leiasp/$',
  path: '/api/leiasp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCupiditysSplatRoute = ApiCupiditysSplatRouteImport.update({
  id: '/api/cupiditys/$',
  path: '/api/cupiditys/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalystCompleteRoute = ApiCatalystCompleteRouteImport.update({
  id: '/api/catalyst/complete',
  path: '/api/catalyst/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalystJobJobIdRoute = ApiCatalystJobJobIdRouteImport.update({
  id: '/api/catalyst/job/$jobId',
  path: '/api/catalyst/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/pdf-proxy': typeof ApiPdfProxyRoute
  '/dashboard/apostilas': typeof DashboardApostilasRoute
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/preparasp': typeof DashboardPreparaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/cupiditys/$': typeof ApiCupiditysSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/preparasp/$': typeof ApiPreparaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/pdf-proxy': typeof ApiPdfProxyRoute
  '/dashboard/apostilas': typeof DashboardApostilasRoute
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/preparasp': typeof DashboardPreparaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/cupiditys/$': typeof ApiCupiditysSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/preparasp/$': typeof ApiPreparaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/pdf-proxy': typeof ApiPdfProxyRoute
  '/dashboard/apostilas': typeof DashboardApostilasRoute
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/preparasp': typeof DashboardPreparaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/cupiditys/$': typeof ApiCupiditysSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/preparasp/$': typeof ApiPreparaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/pdf-proxy'
    | '/dashboard/apostilas'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/preparasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard/'
    | '/api/ai/generate'
    | '/api/catalyst/complete'
    | '/api/cupiditys/$'
    | '/api/leiasp/$'
    | '/api/preparasp/$'
    | '/api/proxy/$'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/pdf-proxy'
    | '/dashboard/apostilas'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/preparasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard'
    | '/api/ai/generate'
    | '/api/catalyst/complete'
    | '/api/cupiditys/$'
    | '/api/leiasp/$'
    | '/api/preparasp/$'
    | '/api/proxy/$'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/pdf-proxy'
    | '/dashboard/apostilas'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/preparasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard/'
    | '/api/ai/generate'
    | '/api/catalyst/complete'
    | '/api/cupiditys/$'
    | '/api/leiasp/$'
    | '/api/preparasp/$'
    | '/api/proxy/$'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiPdfProxyRoute: typeof ApiPdfProxyRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiCatalystCompleteRoute: typeof ApiCatalystCompleteRoute
  ApiCupiditysSplatRoute: typeof ApiCupiditysSplatRoute
  ApiLeiaspSplatRoute: typeof ApiLeiaspSplatRoute
  ApiPreparaspSplatRoute: typeof ApiPreparaspSplatRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  ApiStatusEndpointRoute: typeof ApiStatusEndpointRoute
  ApiCatalystJobJobIdRoute: typeof ApiCatalystJobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tarefas': {
      id: '/dashboard/tarefas'
      path: '/tarefas'
      fullPath: '/dashboard/tarefas'
      preLoaderRoute: typeof DashboardTarefasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/status': {
      id: '/dashboard/status'
      path: '/status'
      fullPath: '/dashboard/status'
      preLoaderRoute: typeof DashboardStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/redacao': {
      id: '/dashboard/redacao'
      path: '/redacao'
      fullPath: '/dashboard/redacao'
      preLoaderRoute: typeof DashboardRedacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preparasp': {
      id: '/dashboard/preparasp'
      path: '/preparasp'
      fullPath: '/dashboard/preparasp'
      preLoaderRoute: typeof DashboardPreparaspRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leiasp': {
      id: '/dashboard/leiasp'
      path: '/leiasp'
      fullPath: '/dashboard/leiasp'
      preLoaderRoute: typeof DashboardLeiaspRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/khan': {
      id: '/dashboard/khan'
      path: '/khan'
      fullPath: '/dashboard/khan'
      preLoaderRoute: typeof DashboardKhanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apostilas': {
      id: '/dashboard/apostilas'
      path: '/apostilas'
      fullPath: '/dashboard/apostilas'
      preLoaderRoute: typeof DashboardApostilasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/pdf-proxy': {
      id: '/api/pdf-proxy'
      path: '/api/pdf-proxy'
      fullPath: '/api/pdf-proxy'
      preLoaderRoute: typeof ApiPdfProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status/$endpoint': {
      id: '/api/status/$endpoint'
      path: '/api/status/$endpoint'
      fullPath: '/api/status/$endpoint'
      preLoaderRoute: typeof ApiStatusEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preparasp/$': {
      id: '/api/preparasp/$'
      path: '/api/preparasp/$'
      fullPath: '/api/preparasp/$'
      preLoaderRoute: typeof ApiPreparaspSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leiasp/$': {
      id: '/api/leiasp/$'
      path: '/api/leiasp/$'
      fullPath: '/api/leiasp/$'
      preLoaderRoute: typeof ApiLeiaspSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cupiditys/$': {
      id: '/api/cupiditys/$'
      path: '/api/cupiditys/$'
      fullPath: '/api/cupiditys/$'
      preLoaderRoute: typeof ApiCupiditysSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalyst/complete': {
      id: '/api/catalyst/complete'
      path: '/api/catalyst/complete'
      fullPath: '/api/catalyst/complete'
      preLoaderRoute: typeof ApiCatalystCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalyst/job/$jobId': {
      id: '/api/catalyst/job/$jobId'
      path: '/api/catalyst/job/$jobId'
      fullPath: '/api/catalyst/job/$jobId'
      preLoaderRoute: typeof ApiCatalystJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardApostilasRoute: typeof DashboardApostilasRoute
  DashboardKhanRoute: typeof DashboardKhanRoute
  DashboardLeiaspRoute: typeof DashboardLeiaspRoute
  DashboardPreparaspRoute: typeof DashboardPreparaspRoute
  DashboardRedacaoRoute: typeof DashboardRedacaoRoute
  DashboardStatusRoute: typeof DashboardStatusRoute
  DashboardTarefasRoute: typeof DashboardTarefasRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApostilasRoute: DashboardApostilasRoute,
  DashboardKhanRoute: DashboardKhanRoute,
  DashboardLeiaspRoute: DashboardLeiaspRoute,
  DashboardPreparaspRoute: DashboardPreparaspRoute,
  DashboardRedacaoRoute: DashboardRedacaoRoute,
  DashboardStatusRoute: DashboardStatusRoute,
  DashboardTarefasRoute: DashboardTarefasRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiPdfProxyRoute: ApiPdfProxyRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiCatalystCompleteRoute: ApiCatalystCompleteRoute,
  ApiCupiditysSplatRoute: ApiCupiditysSplatRoute,
  ApiLeiaspSplatRoute: ApiLeiaspSplatRoute,
  ApiPreparaspSplatRoute: ApiPreparaspSplatRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  ApiStatusEndpointRoute: ApiStatusEndpointRoute,
  ApiCatalystJobJobIdRoute: ApiCatalystJobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
