/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTarefasRouteImport } from './routes/dashboard/tarefas'
import { Route as DashboardStatusRouteImport } from './routes/dashboard/status'
import { Route as DashboardRedacaoRouteImport } from './routes/dashboard/redacao'
import { Route as DashboardLeiaspRouteImport } from './routes/dashboard/leiasp'
import { Route as DashboardKhanRouteImport } from './routes/dashboard/khan'
import { Route as ApiStatusEndpointRouteImport } from './routes/api/status.$endpoint'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy.$'
import { Route as ApiLeiaspSplatRouteImport } from './routes/api/leiasp.$'
import { Route as ApiKhanSplatRouteImport } from './routes/api/khan.$'
import { Route as ApiCatalystCompleteRouteImport } from './routes/api/catalyst.complete'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai.generate'
import { Route as ApiCatalystJobJobIdRouteImport } from './routes/api/catalyst.job.$jobId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTarefasRoute = DashboardTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatusRoute = DashboardStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRedacaoRoute = DashboardRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeiaspRoute = DashboardLeiaspRouteImport.update({
  id: '/leiasp',
  path: '/leiasp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKhanRoute = DashboardKhanRouteImport.update({
  id: '/khan',
  path: '/khan',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStatusEndpointRoute = ApiStatusEndpointRouteImport.update({
  id: '/api/status/$endpoint',
  path: '/api/status/$endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeiaspSplatRoute = ApiLeiaspSplatRouteImport.update({
  id: '/api/leiasp/$',
  path: '/api/leiasp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKhanSplatRoute = ApiKhanSplatRouteImport.update({
  id: '/api/khan/$',
  path: '/api/khan/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalystCompleteRoute = ApiCatalystCompleteRouteImport.update({
  id: '/api/catalyst/complete',
  path: '/api/catalyst/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalystJobJobIdRoute = ApiCatalystJobJobIdRouteImport.update({
  id: '/api/catalyst/job/$jobId',
  path: '/api/catalyst/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/khan/$': typeof ApiKhanSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/khan/$': typeof ApiKhanSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/khan/$': typeof ApiKhanSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard/'
    | '/api/ai/generate'
    | '/api/catalyst/complete'
    | '/api/khan/$'
    | '/api/leiasp/$'
    | '/api/proxy/$'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard'
    | '/api/ai/generate'
    | '/api/catalyst/complete'
    | '/api/khan/$'
    | '/api/leiasp/$'
    | '/api/proxy/$'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard/'
    | '/api/ai/generate'
    | '/api/catalyst/complete'
    | '/api/khan/$'
    | '/api/leiasp/$'
    | '/api/proxy/$'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiCatalystCompleteRoute: typeof ApiCatalystCompleteRoute
  ApiKhanSplatRoute: typeof ApiKhanSplatRoute
  ApiLeiaspSplatRoute: typeof ApiLeiaspSplatRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  ApiStatusEndpointRoute: typeof ApiStatusEndpointRoute
  ApiCatalystJobJobIdRoute: typeof ApiCatalystJobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tarefas': {
      id: '/dashboard/tarefas'
      path: '/tarefas'
      fullPath: '/dashboard/tarefas'
      preLoaderRoute: typeof DashboardTarefasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/status': {
      id: '/dashboard/status'
      path: '/status'
      fullPath: '/dashboard/status'
      preLoaderRoute: typeof DashboardStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/redacao': {
      id: '/dashboard/redacao'
      path: '/redacao'
      fullPath: '/dashboard/redacao'
      preLoaderRoute: typeof DashboardRedacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leiasp': {
      id: '/dashboard/leiasp'
      path: '/leiasp'
      fullPath: '/dashboard/leiasp'
      preLoaderRoute: typeof DashboardLeiaspRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/khan': {
      id: '/dashboard/khan'
      path: '/khan'
      fullPath: '/dashboard/khan'
      preLoaderRoute: typeof DashboardKhanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/status/$endpoint': {
      id: '/api/status/$endpoint'
      path: '/api/status/$endpoint'
      fullPath: '/api/status/$endpoint'
      preLoaderRoute: typeof ApiStatusEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leiasp/$': {
      id: '/api/leiasp/$'
      path: '/api/leiasp/$'
      fullPath: '/api/leiasp/$'
      preLoaderRoute: typeof ApiLeiaspSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/khan/$': {
      id: '/api/khan/$'
      path: '/api/khan/$'
      fullPath: '/api/khan/$'
      preLoaderRoute: typeof ApiKhanSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalyst/complete': {
      id: '/api/catalyst/complete'
      path: '/api/catalyst/complete'
      fullPath: '/api/catalyst/complete'
      preLoaderRoute: typeof ApiCatalystCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalyst/job/$jobId': {
      id: '/api/catalyst/job/$jobId'
      path: '/api/catalyst/job/$jobId'
      fullPath: '/api/catalyst/job/$jobId'
      preLoaderRoute: typeof ApiCatalystJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardKhanRoute: typeof DashboardKhanRoute
  DashboardLeiaspRoute: typeof DashboardLeiaspRoute
  DashboardRedacaoRoute: typeof DashboardRedacaoRoute
  DashboardStatusRoute: typeof DashboardStatusRoute
  DashboardTarefasRoute: typeof DashboardTarefasRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardKhanRoute: DashboardKhanRoute,
  DashboardLeiaspRoute: DashboardLeiaspRoute,
  DashboardRedacaoRoute: DashboardRedacaoRoute,
  DashboardStatusRoute: DashboardStatusRoute,
  DashboardTarefasRoute: DashboardTarefasRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiCatalystCompleteRoute: ApiCatalystCompleteRoute,
  ApiKhanSplatRoute: ApiKhanSplatRoute,
  ApiLeiaspSplatRoute: ApiLeiaspSplatRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  ApiStatusEndpointRoute: ApiStatusEndpointRoute,
  ApiCatalystJobJobIdRoute: ApiCatalystJobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
