/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTarefasRouteImport } from './routes/dashboard/tarefas'
import { Route as DashboardStatusRouteImport } from './routes/dashboard/status'
import { Route as DashboardRedacaoRouteImport } from './routes/dashboard/redacao'
import { Route as DashboardPreparaspRouteImport } from './routes/dashboard/preparasp'
import { Route as DashboardLeiaspRouteImport } from './routes/dashboard/leiasp'
import { Route as DashboardKhanRouteImport } from './routes/dashboard/khan'
import { Route as DashboardBoletimRouteImport } from './routes/dashboard/boletim'
import { Route as DashboardApostilasRouteImport } from './routes/dashboard/apostilas'
import { Route as ApiPdfProxyRouteImport } from './routes/api/pdf-proxy'
import { Route as ApiStatusEndpointRouteImport } from './routes/api/status.$endpoint'
import { Route as ApiRedacaoSubmitRouteImport } from './routes/api/redacao.submit'
import { Route as ApiRedacaoGenerateRouteImport } from './routes/api/redacao.generate'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy.$'
import { Route as ApiPreparaspSplatRouteImport } from './routes/api/preparasp.$'
import { Route as ApiLeiaspSplatRouteImport } from './routes/api/leiasp.$'
import { Route as ApiCupiditysSplatRouteImport } from './routes/api/cupiditys.$'
import { Route as ApiCatalystCompleteRouteImport } from './routes/api/catalyst.complete'
import { Route as ApiBoletimSplatRouteImport } from './routes/api/boletim.$'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai.generate'
import { Route as ApiAdminVerifyRouteImport } from './routes/api/admin.verify'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin.settings'
import { Route as ApiAdminLogsRouteImport } from './routes/api/admin.logs'
import { Route as ApiCatalystJobJobIdRouteImport } from './routes/api/catalyst.job.$jobId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTarefasRoute = DashboardTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatusRoute = DashboardStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRedacaoRoute = DashboardRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreparaspRoute = DashboardPreparaspRouteImport.update({
  id: '/preparasp',
  path: '/preparasp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeiaspRoute = DashboardLeiaspRouteImport.update({
  id: '/leiasp',
  path: '/leiasp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKhanRoute = DashboardKhanRouteImport.update({
  id: '/khan',
  path: '/khan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBoletimRoute = DashboardBoletimRouteImport.update({
  id: '/boletim',
  path: '/boletim',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApostilasRoute = DashboardApostilasRouteImport.update({
  id: '/apostilas',
  path: '/apostilas',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPdfProxyRoute = ApiPdfProxyRouteImport.update({
  id: '/api/pdf-proxy',
  path: '/api/pdf-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusEndpointRoute = ApiStatusEndpointRouteImport.update({
  id: '/api/status/$endpoint',
  path: '/api/status/$endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedacaoSubmitRoute = ApiRedacaoSubmitRouteImport.update({
  id: '/api/redacao/submit',
  path: '/api/redacao/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedacaoGenerateRoute = ApiRedacaoGenerateRouteImport.update({
  id: '/api/redacao/generate',
  path: '/api/redacao/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreparaspSplatRoute = ApiPreparaspSplatRouteImport.update({
  id: '/api/preparasp/$',
  path: '/api/preparasp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeiaspSplatRoute = ApiLeiaspSplatRouteImport.update({
  id: '/api/leiasp/$',
  path: '/api/leiasp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCupiditysSplatRoute = ApiCupiditysSplatRouteImport.update({
  id: '/api/cupiditys/$',
  path: '/api/cupiditys/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalystCompleteRoute = ApiCatalystCompleteRouteImport.update({
  id: '/api/catalyst/complete',
  path: '/api/catalyst/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoletimSplatRoute = ApiBoletimSplatRouteImport.update({
  id: '/api/boletim/$',
  path: '/api/boletim/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyRoute = ApiAdminVerifyRouteImport.update({
  id: '/api/admin/verify',
  path: '/api/admin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogsRoute = ApiAdminLogsRouteImport.update({
  id: '/api/admin/logs',
  path: '/api/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalystJobJobIdRoute = ApiCatalystJobJobIdRouteImport.update({
  id: '/api/catalyst/job/$jobId',
  path: '/api/catalyst/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/termos': typeof TermosRoute
  '/api/pdf-proxy': typeof ApiPdfProxyRoute
  '/dashboard/apostilas': typeof DashboardApostilasRoute
  '/dashboard/boletim': typeof DashboardBoletimRoute
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/preparasp': typeof DashboardPreparaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/boletim/$': typeof ApiBoletimSplatRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/cupiditys/$': typeof ApiCupiditysSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/preparasp/$': typeof ApiPreparaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/redacao/generate': typeof ApiRedacaoGenerateRoute
  '/api/redacao/submit': typeof ApiRedacaoSubmitRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/termos': typeof TermosRoute
  '/api/pdf-proxy': typeof ApiPdfProxyRoute
  '/dashboard/apostilas': typeof DashboardApostilasRoute
  '/dashboard/boletim': typeof DashboardBoletimRoute
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/preparasp': typeof DashboardPreparaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/boletim/$': typeof ApiBoletimSplatRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/cupiditys/$': typeof ApiCupiditysSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/preparasp/$': typeof ApiPreparaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/redacao/generate': typeof ApiRedacaoGenerateRoute
  '/api/redacao/submit': typeof ApiRedacaoSubmitRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/termos': typeof TermosRoute
  '/api/pdf-proxy': typeof ApiPdfProxyRoute
  '/dashboard/apostilas': typeof DashboardApostilasRoute
  '/dashboard/boletim': typeof DashboardBoletimRoute
  '/dashboard/khan': typeof DashboardKhanRoute
  '/dashboard/leiasp': typeof DashboardLeiaspRoute
  '/dashboard/preparasp': typeof DashboardPreparaspRoute
  '/dashboard/redacao': typeof DashboardRedacaoRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/tarefas': typeof DashboardTarefasRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/boletim/$': typeof ApiBoletimSplatRoute
  '/api/catalyst/complete': typeof ApiCatalystCompleteRoute
  '/api/cupiditys/$': typeof ApiCupiditysSplatRoute
  '/api/leiasp/$': typeof ApiLeiaspSplatRoute
  '/api/preparasp/$': typeof ApiPreparaspSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/redacao/generate': typeof ApiRedacaoGenerateRoute
  '/api/redacao/submit': typeof ApiRedacaoSubmitRoute
  '/api/status/$endpoint': typeof ApiStatusEndpointRoute
  '/api/catalyst/job/$jobId': typeof ApiCatalystJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/termos'
    | '/api/pdf-proxy'
    | '/dashboard/apostilas'
    | '/dashboard/boletim'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/preparasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard/'
    | '/api/admin/logs'
    | '/api/admin/settings'
    | '/api/admin/verify'
    | '/api/ai/generate'
    | '/api/boletim/$'
    | '/api/catalyst/complete'
    | '/api/cupiditys/$'
    | '/api/leiasp/$'
    | '/api/preparasp/$'
    | '/api/proxy/$'
    | '/api/redacao/generate'
    | '/api/redacao/submit'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/termos'
    | '/api/pdf-proxy'
    | '/dashboard/apostilas'
    | '/dashboard/boletim'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/preparasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard'
    | '/api/admin/logs'
    | '/api/admin/settings'
    | '/api/admin/verify'
    | '/api/ai/generate'
    | '/api/boletim/$'
    | '/api/catalyst/complete'
    | '/api/cupiditys/$'
    | '/api/leiasp/$'
    | '/api/preparasp/$'
    | '/api/proxy/$'
    | '/api/redacao/generate'
    | '/api/redacao/submit'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/termos'
    | '/api/pdf-proxy'
    | '/dashboard/apostilas'
    | '/dashboard/boletim'
    | '/dashboard/khan'
    | '/dashboard/leiasp'
    | '/dashboard/preparasp'
    | '/dashboard/redacao'
    | '/dashboard/status'
    | '/dashboard/tarefas'
    | '/dashboard/'
    | '/api/admin/logs'
    | '/api/admin/settings'
    | '/api/admin/verify'
    | '/api/ai/generate'
    | '/api/boletim/$'
    | '/api/catalyst/complete'
    | '/api/cupiditys/$'
    | '/api/leiasp/$'
    | '/api/preparasp/$'
    | '/api/proxy/$'
    | '/api/redacao/generate'
    | '/api/redacao/submit'
    | '/api/status/$endpoint'
    | '/api/catalyst/job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  TermosRoute: typeof TermosRoute
  ApiPdfProxyRoute: typeof ApiPdfProxyRoute
  ApiAdminLogsRoute: typeof ApiAdminLogsRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminVerifyRoute: typeof ApiAdminVerifyRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiBoletimSplatRoute: typeof ApiBoletimSplatRoute
  ApiCatalystCompleteRoute: typeof ApiCatalystCompleteRoute
  ApiCupiditysSplatRoute: typeof ApiCupiditysSplatRoute
  ApiLeiaspSplatRoute: typeof ApiLeiaspSplatRoute
  ApiPreparaspSplatRoute: typeof ApiPreparaspSplatRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  ApiRedacaoGenerateRoute: typeof ApiRedacaoGenerateRoute
  ApiRedacaoSubmitRoute: typeof ApiRedacaoSubmitRoute
  ApiStatusEndpointRoute: typeof ApiStatusEndpointRoute
  ApiCatalystJobJobIdRoute: typeof ApiCatalystJobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tarefas': {
      id: '/dashboard/tarefas'
      path: '/tarefas'
      fullPath: '/dashboard/tarefas'
      preLoaderRoute: typeof DashboardTarefasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/status': {
      id: '/dashboard/status'
      path: '/status'
      fullPath: '/dashboard/status'
      preLoaderRoute: typeof DashboardStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/redacao': {
      id: '/dashboard/redacao'
      path: '/redacao'
      fullPath: '/dashboard/redacao'
      preLoaderRoute: typeof DashboardRedacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preparasp': {
      id: '/dashboard/preparasp'
      path: '/preparasp'
      fullPath: '/dashboard/preparasp'
      preLoaderRoute: typeof DashboardPreparaspRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leiasp': {
      id: '/dashboard/leiasp'
      path: '/leiasp'
      fullPath: '/dashboard/leiasp'
      preLoaderRoute: typeof DashboardLeiaspRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/khan': {
      id: '/dashboard/khan'
      path: '/khan'
      fullPath: '/dashboard/khan'
      preLoaderRoute: typeof DashboardKhanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/boletim': {
      id: '/dashboard/boletim'
      path: '/boletim'
      fullPath: '/dashboard/boletim'
      preLoaderRoute: typeof DashboardBoletimRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apostilas': {
      id: '/dashboard/apostilas'
      path: '/apostilas'
      fullPath: '/dashboard/apostilas'
      preLoaderRoute: typeof DashboardApostilasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/pdf-proxy': {
      id: '/api/pdf-proxy'
      path: '/api/pdf-proxy'
      fullPath: '/api/pdf-proxy'
      preLoaderRoute: typeof ApiPdfProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status/$endpoint': {
      id: '/api/status/$endpoint'
      path: '/api/status/$endpoint'
      fullPath: '/api/status/$endpoint'
      preLoaderRoute: typeof ApiStatusEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/redacao/submit': {
      id: '/api/redacao/submit'
      path: '/api/redacao/submit'
      fullPath: '/api/redacao/submit'
      preLoaderRoute: typeof ApiRedacaoSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/redacao/generate': {
      id: '/api/redacao/generate'
      path: '/api/redacao/generate'
      fullPath: '/api/redacao/generate'
      preLoaderRoute: typeof ApiRedacaoGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preparasp/$': {
      id: '/api/preparasp/$'
      path: '/api/preparasp/$'
      fullPath: '/api/preparasp/$'
      preLoaderRoute: typeof ApiPreparaspSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leiasp/$': {
      id: '/api/leiasp/$'
      path: '/api/leiasp/$'
      fullPath: '/api/leiasp/$'
      preLoaderRoute: typeof ApiLeiaspSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cupiditys/$': {
      id: '/api/cupiditys/$'
      path: '/api/cupiditys/$'
      fullPath: '/api/cupiditys/$'
      preLoaderRoute: typeof ApiCupiditysSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalyst/complete': {
      id: '/api/catalyst/complete'
      path: '/api/catalyst/complete'
      fullPath: '/api/catalyst/complete'
      preLoaderRoute: typeof ApiCatalystCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boletim/$': {
      id: '/api/boletim/$'
      path: '/api/boletim/$'
      fullPath: '/api/boletim/$'
      preLoaderRoute: typeof ApiBoletimSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify': {
      id: '/api/admin/verify'
      path: '/api/admin/verify'
      fullPath: '/api/admin/verify'
      preLoaderRoute: typeof ApiAdminVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logs': {
      id: '/api/admin/logs'
      path: '/api/admin/logs'
      fullPath: '/api/admin/logs'
      preLoaderRoute: typeof ApiAdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalyst/job/$jobId': {
      id: '/api/catalyst/job/$jobId'
      path: '/api/catalyst/job/$jobId'
      fullPath: '/api/catalyst/job/$jobId'
      preLoaderRoute: typeof ApiCatalystJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardApostilasRoute: typeof DashboardApostilasRoute
  DashboardBoletimRoute: typeof DashboardBoletimRoute
  DashboardKhanRoute: typeof DashboardKhanRoute
  DashboardLeiaspRoute: typeof DashboardLeiaspRoute
  DashboardPreparaspRoute: typeof DashboardPreparaspRoute
  DashboardRedacaoRoute: typeof DashboardRedacaoRoute
  DashboardStatusRoute: typeof DashboardStatusRoute
  DashboardTarefasRoute: typeof DashboardTarefasRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApostilasRoute: DashboardApostilasRoute,
  DashboardBoletimRoute: DashboardBoletimRoute,
  DashboardKhanRoute: DashboardKhanRoute,
  DashboardLeiaspRoute: DashboardLeiaspRoute,
  DashboardPreparaspRoute: DashboardPreparaspRoute,
  DashboardRedacaoRoute: DashboardRedacaoRoute,
  DashboardStatusRoute: DashboardStatusRoute,
  DashboardTarefasRoute: DashboardTarefasRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  TermosRoute: TermosRoute,
  ApiPdfProxyRoute: ApiPdfProxyRoute,
  ApiAdminLogsRoute: ApiAdminLogsRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminVerifyRoute: ApiAdminVerifyRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiBoletimSplatRoute: ApiBoletimSplatRoute,
  ApiCatalystCompleteRoute: ApiCatalystCompleteRoute,
  ApiCupiditysSplatRoute: ApiCupiditysSplatRoute,
  ApiLeiaspSplatRoute: ApiLeiaspSplatRoute,
  ApiPreparaspSplatRoute: ApiPreparaspSplatRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  ApiRedacaoGenerateRoute: ApiRedacaoGenerateRoute,
  ApiRedacaoSubmitRoute: ApiRedacaoSubmitRoute,
  ApiStatusEndpointRoute: ApiStatusEndpointRoute,
  ApiCatalystJobJobIdRoute: ApiCatalystJobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
